---
default_stages: [pre-commit]
repos:
  # General Hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-symlinks
      - id: forbid-submodules
      - id: forbid-new-submodules
      - id: check-toml
  # YAML Hooks
  - repo: https://github.com/google/yamlfmt.git
    rev: v0.20.0
    hooks:
      - id: yamlfmt
        args: ['-conf', './.config/yamlfmt.yaml']
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
        args: ['--strict', '-c', './.config/yamllint.yaml']
  # Shell Hooks
  - repo: local
    hooks:
      - name: shellcheck
        id: shellcheck
        description: Test shell scripts with shellcheck
        entry: mise exec -E dev -- shellcheck
        language: python
        types: [shell]
        require_serial: true
  # Git Hooks
  - repo: https://github.com/commit-check/commit-check
    rev: v2.6.0
    hooks:
      - id: check-message
      - id: check-branch
